<?php
declare(strict_types=1);
require __DIR__.'/config.php'; require __DIR__.'/auth.php'; header('Content-Type: application/json; charset=utf-8'); require_login_json();
function respond(int $code,array $p):void{http_response_code($code);echo json_encode($p,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function tableExists(PDO $pdo,string $table):bool{$s=$pdo->prepare("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=:t");$s->execute([':t'=>$table]);return (int)$s->fetchColumn()>0;}
function moneyText(float $n):string{return 'Rs. '.number_format($n);}
try{$pdo=db();$uid=(int)$_SESSION['user_id'];
$s=$pdo->prepare('SELECT full_name FROM users WHERE id=:id LIMIT 1');$s->execute([':id'=>$uid]);$u=$s->fetch();if(!$u)respond(404,['success'=>false,'message'=>'Account not found.']);
$s=$pdo->prepare('SELECT * FROM wedding_details WHERE user_id=:uid LIMIT 1');$s->execute([':uid'=>$uid]);$wd=$s->fetch();if(!$wd){$pdo->prepare('INSERT INTO wedding_details(user_id) VALUES(:uid)')->execute([':uid'=>$uid]);$wd=['bride_name'=>'','groom_name'=>'','partner_name'=>'','wedding_date'=>null,'total_budget'=>0,'spent_budget'=>0];}
$bride=trim((string)($wd['bride_name']??''));$groom=trim((string)($wd['groom_name']??''));$partner=trim((string)($wd['partner_name']??''));$full=trim((string)$u['full_name']);$couple=$bride&&$groom?"$bride & $groom":($bride?:($groom?:($partner?"$full & $partner":$full)));
$days=null;$dateText='Not set yet';if(!empty($wd['wedding_date'])){try{$d=new DateTime((string)$wd['wedding_date']);$today=new DateTime('today');$diff=$today->diff($d);$days=$diff->invert?0:(int)$diff->days;$dateText=$d->format('jS F Y');}catch(Throwable $e){}}
$tasksTotal=$tasksDone=0;$upcoming=[];if(tableExists($pdo,'tasks')){$s=$pdo->prepare("SELECT COUNT(*) total, COALESCE(SUM(status='Completed'),0) done FROM tasks WHERE user_id=:uid");$s->execute([':uid'=>$uid]);$r=$s->fetch();$tasksTotal=(int)$r['total'];$tasksDone=(int)$r['done'];$s=$pdo->prepare("SELECT title,due_date,status FROM tasks WHERE user_id=:uid AND status<>'Completed' ORDER BY due_date IS NULL ASC,due_date ASC,id ASC LIMIT 5");$s->execute([':uid'=>$uid]);foreach($s->fetchAll() as $r)$upcoming[]=['title'=>(string)$r['title'],'due_date'=>!empty($r['due_date'])?date('d M Y',strtotime($r['due_date'])):'','status'=>(string)$r['status']];}
$total=(float)($wd['total_budget']??0);$spent=(float)($wd['spent_budget']??0);if(tableExists($pdo,'budget_items')){$s=$pdo->prepare('SELECT COALESCE(SUM(estimated),0) est, COALESCE(SUM(actual),0) act FROM budget_items WHERE user_id=:uid');$s->execute([':uid'=>$uid]);$br=$s->fetch();$budgetEst=(float)$br['est'];$budgetActual=(float)$br['act'];if($total<=0)$total=$budgetEst;if($budgetActual>0||$total>0)$spent=$budgetActual;}
$remaining=max($total-$spent,0);$pct=$total>0?(int)round($spent/$total*100):0;$pct=max(0,min(100,$pct));
$guestsConfirmed=0;if(tableExists($pdo,'guests')){$s=$pdo->prepare("SELECT COUNT(*) FROM guests WHERE user_id=:uid AND rsvp='Confirmed'");$s->execute([':uid'=>$uid]);$guestsConfirmed=(int)$s->fetchColumn();}else{$guestsConfirmed=(int)($wd['guests_confirmed']??0);}
$vendorsSaved=0;if(tableExists($pdo,'vendors')){$s=$pdo->prepare('SELECT COUNT(*) FROM vendors WHERE user_id=:uid');$s->execute([':uid'=>$uid]);$vendorsSaved=(int)$s->fetchColumn();}else{$vendorsSaved=(int)($wd['vendors_saved']??0);}
$payments=[];if(tableExists($pdo,'payments')){$pdo->prepare("UPDATE payments SET status='overdue' WHERE user_id=:uid AND status='upcoming' AND due_date IS NOT NULL AND due_date < CURDATE()")->execute([':uid'=>$uid]);$s=$pdo->prepare("SELECT payment_name,amount,due_date FROM payments WHERE user_id=:uid AND status='upcoming' ORDER BY due_date IS NULL ASC,due_date ASC LIMIT 5");$s->execute([':uid'=>$uid]);foreach($s->fetchAll() as $r)$payments[]=['name'=>$r['payment_name'],'amount'=>moneyText((float)$r['amount']),'due_date'=>!empty($r['due_date'])?date('d M Y',strtotime($r['due_date'])):''];}
respond(200,['success'=>true,'user'=>['full_name'=>$full,'couple_name'=>$couple],'wedding'=>['date'=>$dateText,'days_to_go'=>$days],'stats'=>['tasks_done'=>$tasksDone,'tasks_total'=>$tasksTotal,'tasks_progress'=>$tasksTotal?(int)round($tasksDone/$tasksTotal*100):0,'budget_spent'=>moneyText($spent),'budget_total'=>number_format($total),'budget_pct'=>$pct,'guests_confirmed'=>$guestsConfirmed,'vendors_saved'=>$vendorsSaved],'budget_overview'=>['total'=>moneyText($total),'spent'=>moneyText($spent),'remaining'=>moneyText($remaining),'spent_pct'=>$pct],'upcoming_tasks'=>$upcoming,'upcoming_payments'=>$payments]);
}catch(Throwable $e){error_log('[WEDORA dashboard_data] '.$e->getMessage());respond(500,['success'=>false,'message'=>'Could not load your dashboard right now. Please check the database and try again.']);}
