<?php
declare(strict_types=1);
require __DIR__.'/config.php'; require __DIR__.'/auth.php'; header('Content-Type: application/json; charset=utf-8'); require_login_json();
function respond(int $code,array $data):void{http_response_code($code);echo json_encode($data,JSON_UNESCAPED_UNICODE);exit;}
function body():array{$d=json_decode(file_get_contents('php://input')?:'{}',true);return is_array($d)?$d:[];}
function priority(string $v):string{return in_array($v,['Low','Medium','High'],true)?$v:'Medium';}
function statusValue(string $v):string{return in_array($v,['To Do','In Progress','Completed'],true)?$v:'To Do';}
function fmt($d):string{if(!$d)return ''; $t=strtotime((string)$d);return $t?date('d M Y',$t):(string)$d;}
try{$pdo=db();$uid=(int)$_SESSION['user_id'];$pdo->exec("CREATE TABLE IF NOT EXISTS tasks(id INT UNSIGNED NOT NULL AUTO_INCREMENT,user_id INT UNSIGNED NULL,title VARCHAR(200) NOT NULL,category VARCHAR(100) NOT NULL DEFAULT 'General',due_date DATE NULL,priority ENUM('Low','Medium','High') NOT NULL DEFAULT 'Medium',status ENUM('To Do','In Progress','Completed') NOT NULL DEFAULT 'To Do',notes TEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_tasks_user(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$method=$_SERVER['REQUEST_METHOD'];
if($method==='GET'){
 $id=(int)($_GET['id']??0);if($id){$s=$pdo->prepare('SELECT * FROM tasks WHERE id=:id AND user_id=:uid LIMIT 1');$s->execute([':id'=>$id,':uid'=>$uid]);$t=$s->fetch();if(!$t)respond(404,['success'=>false,'message'=>'Task not found.']);$t['formatted_due_date']=fmt($t['due_date']);respond(200,['success'=>true,'data'=>$t]);}
 $where=['user_id=:uid'];$params=[':uid'=>$uid];$status=trim((string)($_GET['status']??''));$priority=trim((string)($_GET['priority']??''));$search=trim((string)($_GET['search']??''));
 if($status!==''&&strtolower($status)!=='all'){$where[]='status=:status';$params[':status']=statusValue($status);}if($priority!==''&&strtolower($priority)!=='all'){$where[]='priority=:priority';$params[':priority']=priority($priority);}if($search!==''){$where[]='(title LIKE :q OR category LIKE :q)';$params[':q']='%'.$search.'%';}
 $s=$pdo->prepare('SELECT * FROM tasks WHERE '.implode(' AND ',$where).' ORDER BY due_date IS NULL ASC,due_date ASC,id ASC');$s->execute($params);$tasks=$s->fetchAll();foreach($tasks as &$t)$t['formatted_due_date']=fmt($t['due_date']);unset($t);respond(200,['success'=>true,'data'=>$tasks,'count'=>count($tasks)]);
}
if($method==='POST'){$b=body();$title=trim((string)($b['title']??''));if($title==='')respond(422,['success'=>false,'message'=>'Task title is required.']);$due=trim((string)($b['due_date']??''));$s=$pdo->prepare('INSERT INTO tasks(user_id,title,category,due_date,priority,status,notes) VALUES(:uid,:title,:cat,:due,:priority,:status,:notes)');$s->execute([':uid'=>$uid,':title'=>$title,':cat'=>trim((string)($b['category']??'General'))?:'General',':due'=>$due?:null,':priority'=>priority((string)($b['priority']??'Medium')),':status'=>statusValue((string)($b['status']??'To Do')),':notes'=>trim((string)($b['notes']??''))?:null]);$id=(int)$pdo->lastInsertId();$s=$pdo->prepare('SELECT * FROM tasks WHERE id=:id AND user_id=:uid');$s->execute([':id'=>$id,':uid'=>$uid]);$t=$s->fetch();$t['formatted_due_date']=fmt($t['due_date']);respond(201,['success'=>true,'message'=>'Task created successfully.','data'=>$t]);}
if($method==='PUT'){$id=(int)($_GET['id']??0);$b=body();if(!$id)$id=(int)($b['id']??0);if(!$id)respond(422,['success'=>false,'message'=>'Task id is required.']);$allowed=['title','category','due_date','priority','status','notes'];$set=[];$params=[];foreach($allowed as $f){if(array_key_exists($f,$b)){$v=$b[$f];if($f==='priority')$v=priority((string)$v);if($f==='status')$v=statusValue((string)$v);if(in_array($f,['title','category'],true))$v=trim((string)$v);$set[]="`$f`=:v_$f";$params[":v_$f"]=$v===''?null:$v;}}if(!$set)respond(422,['success'=>false,'message'=>'No fields provided to update.']);$params[':id']=$id;$params[':uid']=$uid;$s=$pdo->prepare('UPDATE tasks SET '.implode(',',$set).' WHERE id=:id AND user_id=:uid');$s->execute($params);if($s->rowCount()===0){$c=$pdo->prepare('SELECT id FROM tasks WHERE id=:id AND user_id=:uid');$c->execute([':id'=>$id,':uid'=>$uid]);if(!$c->fetch())respond(404,['success'=>false,'message'=>'Task not found.']);}$s=$pdo->prepare('SELECT * FROM tasks WHERE id=:id AND user_id=:uid');$s->execute([':id'=>$id,':uid'=>$uid]);$t=$s->fetch();$t['formatted_due_date']=fmt($t['due_date']);respond(200,['success'=>true,'message'=>'Task updated successfully.','data'=>$t]);}
if($method==='DELETE'){$id=(int)($_GET['id']??0);if(!$id)respond(422,['success'=>false,'message'=>'Task id is required.']);$s=$pdo->prepare('DELETE FROM tasks WHERE id=:id AND user_id=:uid');$s->execute([':id'=>$id,':uid'=>$uid]);if($s->rowCount()===0)respond(404,['success'=>false,'message'=>'Task not found.']);respond(200,['success'=>true,'message'=>'Task deleted successfully.']);}
respond(405,['success'=>false,'message'=>'Method not allowed.']);
}catch(Throwable $e){error_log('[WEDORA tasks] '.$e->getMessage());respond(500,['success'=>false,'message'=>'Could not process tasks right now.']);}
