<?php
declare(strict_types=1);
require __DIR__.'/config.php'; require __DIR__.'/auth.php'; header('Content-Type: application/json; charset=utf-8'); require_login_json();
function respond(int $status,array $payload):void{http_response_code($status);echo json_encode($payload,JSON_UNESCAPED_UNICODE);exit;}
const VENDOR_CATEGORIES=['Photography','Videography','Venue','Catering','Decorations','Florist','Others'];
function readJsonOrPost():array{$raw=file_get_contents('php://input');$d=$raw?json_decode($raw,true):null;return is_array($d)?$d:$_POST;}
function validateVendorInput(array $d):array{$e=[];$name=trim((string)($d['name']??''));$cat=trim((string)($d['category']??''));$contact=trim((string)($d['contact']??''));$price=trim((string)($d['price']??''));$notes=trim((string)($d['notes']??''));if($name==='')$e['name']='Vendor name is required.';elseif(mb_strlen($name)>150)$e['name']='Vendor name is too long.';if(!in_array($cat,VENDOR_CATEGORIES,true))$e['category']='Please choose a valid category.';if($contact===''||mb_strlen($contact)>30)$e['contact']='Enter a valid contact number.';if($price===''||!is_numeric($price)||(float)$price<0)$e['price']='Enter a valid price.';return [['name'=>$name,'category'=>$cat,'contact'=>$contact,'price'=>$price!==''?(float)$price:0,'notes'=>$notes?:null],$e];}
try{$pdo=db();$uid=(int)$_SESSION['user_id'];$pdo->exec("CREATE TABLE IF NOT EXISTS vendors(id INT UNSIGNED NOT NULL AUTO_INCREMENT,name VARCHAR(150) NOT NULL,category VARCHAR(50) NOT NULL,contact VARCHAR(30) NOT NULL,price DECIMAL(12,2) NOT NULL DEFAULT 0,notes VARCHAR(255) NULL,user_id INT UNSIGNED NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_vendors_user(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$action=$_GET['action']??$_POST['action']??'';
if($action==='list'){$cat=trim((string)($_GET['category']??''));$q=trim((string)($_GET['q']??''));$where=['user_id=:uid'];$params=[':uid'=>$uid];if($cat!==''&&$cat!=='All'){$where[]='category=:cat';$params[':cat']=$cat;}if($q!==''){$where[]='(name LIKE :q OR category LIKE :q OR contact LIKE :q)';$params[':q']='%'.$q.'%';}$s=$pdo->prepare('SELECT id,name,category,contact,price,notes,created_at FROM vendors WHERE '.implode(' AND ',$where).' ORDER BY created_at DESC,id DESC');$s->execute($params);respond(200,['success'=>true,'vendors'=>$s->fetchAll()]);}
if($action==='get'){$id=(int)($_GET['id']??0);$s=$pdo->prepare('SELECT id,name,category,contact,price,notes,created_at FROM vendors WHERE id=:id AND user_id=:uid LIMIT 1');$s->execute([':id'=>$id,':uid'=>$uid]);$v=$s->fetch();if(!$v)respond(404,['success'=>false,'message'=>'Vendor not found.']);respond(200,['success'=>true,'vendor'=>$v]);}
if(in_array($action,['add','update','delete'],true)&&$_SERVER['REQUEST_METHOD']!=='POST')respond(405,['success'=>false,'message'=>'Method not allowed.']);
if($action==='add'){[$c,$e]=validateVendorInput(readJsonOrPost());if($e)respond(422,['success'=>false,'message'=>'Please fix the errors below.','errors'=>$e]);$s=$pdo->prepare('INSERT INTO vendors(name,category,contact,price,notes,user_id) VALUES(:name,:cat,:contact,:price,:notes,:uid)');$s->execute([':name'=>$c['name'],':cat'=>$c['category'],':contact'=>$c['contact'],':price'=>$c['price'],':notes'=>$c['notes'],':uid'=>$uid]);respond(201,['success'=>true,'message'=>'Vendor added successfully.','id'=>(int)$pdo->lastInsertId()]);}
if($action==='update'){$data=readJsonOrPost();[$c,$e]=validateVendorInput($data);$id=(int)($data['id']??0);if($id<=0)respond(422,['success'=>false,'message'=>'A valid vendor id is required.']);if($e)respond(422,['success'=>false,'message'=>'Please fix the errors below.','errors'=>$e]);$s=$pdo->prepare('UPDATE vendors SET name=:name,category=:cat,contact=:contact,price=:price,notes=:notes WHERE id=:id AND user_id=:uid');$s->execute([':name'=>$c['name'],':cat'=>$c['category'],':contact'=>$c['contact'],':price'=>$c['price'],':notes'=>$c['notes'],':id'=>$id,':uid'=>$uid]);if($s->rowCount()===0){$c2=$pdo->prepare('SELECT id FROM vendors WHERE id=:id AND user_id=:uid');$c2->execute([':id'=>$id,':uid'=>$uid]);if(!$c2->fetch())respond(404,['success'=>false,'message'=>'Vendor not found.']);}respond(200,['success'=>true,'message'=>'Vendor updated successfully.']);}
if($action==='delete'){$data=readJsonOrPost();$id=(int)($data['id']??0);if($id<=0)respond(422,['success'=>false,'message'=>'A valid vendor id is required.']);$s=$pdo->prepare('DELETE FROM vendors WHERE id=:id AND user_id=:uid');$s->execute([':id'=>$id,':uid'=>$uid]);if(!$s->rowCount())respond(404,['success'=>false,'message'=>'Vendor not found.']);respond(200,['success'=>true,'message'=>'Vendor deleted successfully.']);}
respond(400,['success'=>false,'message'=>'Unknown or missing action.']);
}catch(Throwable $e){error_log('[WEDORA vendors] '.$e->getMessage());respond(500,['success'=>false,'message'=>'Could not process vendors right now.']);}
